### ISSUE TITLE
Passing sub command

### ISSUE THREAD

**Issue by natew** [steelbrain/command#5]
Running this gives error:

```sh
❯ repoman exec -- test
Error TypeError: Cannot read property 'trim' of undefined
    at str.map.call.x (/Users/nw/projects/motion/repoman/node_modules/camelcase/index.js:33:41)
    at Object.map (native)
    at module.exports (/Users/nw/projects/motion/repoman/node_modules/camelcase/index.js:33:19)
    at Command.parse (/Users/nw/projects/motion/repoman/node_modules/sb-command/lib/index.js:159:43)
    at /Users/nw/projects/motion/repoman/lib/cli.js:59:39
```

**Comment by natew** [comment]
(Note added an empty command exec to repoman to test on master).
